### ISSUE TITLE
Laced unable to convert properly 

### ISSUE THREAD

**Issue by KickedYs** [nav17/label_converter#1]

**Comment by KickedYs** [comment]
> Hi when I try to convert a a4 pdf into a 4 by 6 thermal printer dimensions it doesn’t convert properly I have attached the a picture of the issue this is for laced alias works fine 
![70D080BE-F5E1-4A3F-97AD-2099E9976F11](https://user-images.githubusercontent.com/121309487/209374172-6855848f-80e8-4a51-bb24-c675792b7fe9.jpeg)

**Comment by nav17** [comment]
Hi when you download labels from laced what is the file name being saved as? They should end in '- Shipping Label.pdf'

**Comment by KickedYs** [comment]
Nope it’s being saved as new label.pdf i am using an outdated version?

**Comment by nav17** [comment]
I mean the original a4 laced labels you download from the site before adding them in

**Comment by KickedYs** [comment]
Hi no it wasn’t but I think I found the issue I was downloading it from my email rather the website it works perfectly now thanks 🙏🏽

**Comment by nav17** [comment]
No worries if you have any more questions or suggestions feel free to ask 🫡

**Comment by KickedYs** [comment]
Will do thanks
