### ISSUE TITLE
possible new features to add

### ISSUE THREAD

**Issue by KickedYs** [nav17/label_converter#2]
stockx label support
ups alias label support as they now use a mix of dpd or ups and ups labels bug out 
kick game labels support
if you could add these would greatly appreciate it

**Comment by nav17** [comment]
Stockx and ups alias label support have been added :)
Since stockx uses web pages for their labels you will need to print to PDF (right click -> Print -> change printer to PDF) to add those.
Personally haven't used kick game yet but once I sell something there I'll add support for that too

**Comment by KickedYs** [comment]
legend appreciate it if you want i could send a kick game label on discord

**Comment by nav17** [comment]
Sure send it at sengh#0001
